{% set name = "pyout" %}
{% set version = "0.7.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: b1419597af4617886a76a3769577573cecba874f263278474a91269a5ee69138

build:
  number: 2
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - python                              # [build_platform != target_platform]
    - cross-python_{{ target_platform }}  # [build_platform != target_platform]
  host:
    - python
    - pip
    - setuptools
    - pytest-runner
  run:
    - python
    - blessed  # [not win]
    - jsonschema >=3.0.0

test:
  requires:
    - pytest
    - pytest-timeout
  imports:
    - pyout
  commands:
    - python -m pytest -s -v -k "not test_tabular_write_callable_kb_interrupt_in_exit" --pyargs pyout

about:
  home: https://github.com/pyout/pyout
  license: MIT
  license_family: MIT
  license_file: COPYING
  summary: Terminal styling for tabular data
  dev_url: https://github.com/pyout/pyout

extra:
  recipe-maintainers:
    - yarikoptic
    - jwodder
