{% set name = "pyout" %}
{% set version = "0.7.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 1b13359c5497d40586b8049f29325d35a28361d132a23ecaac1561ac09a478a5

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python
    - pip
    - setuptools
    - pytest-runner
  run:
    - python
    - blessings  # [not win]
    - jsonschema >=3.0.0

test:
  requires:
    - pytest
    - pytest-timeout
  imports:
    - pyout
  commands:
    - python -m pytest -s -v -k "not test_tabular_write_callable_kb_interrupt_in_exit" --pyargs pyout

about:
  home: https://github.com/pyout/pyout
  license: MIT
  license_family: MIT
  license_file: COPYING
  summary: Terminal styling for tabular data
  dev_url: https://github.com/pyout/pyout

extra:
  recipe-maintainers:
    - yarikoptic
    - jwodder
